### ISSUE TITLE
disable console logging

### ISSUE THREAD

**Issue by timoly** [andreyvit/json-diff#120]
Latest version has https://github.com/andreyvit/json-diff/blob/fe4c3d9786d73f4c4557df12eca1807b60d21905/lib/index.js#L331 console.log call enabled, which causes output when using the library.

**Comment by ewoudenberg** [comment]
This has been fixed in version 1.0.5

**Comment by laseanb** [comment]
Hey @ewoudenberg , I'm sill seeing this v1.0.5 as well. I see 3 console logs were added in v1.0.4 (https://github.com/andreyvit/json-diff/commit/83f25f491348613b130df727b7e2f6163dec7eec) and 2 were commented out in v1.0.5 (https://github.com/andreyvit/json-diff/pull/118/files) but that last one that @timoly referenced is still present in the master branch.

**Comment by laseanb** [comment]
I created a PR for the tweak if you agree: https://github.com/andreyvit/json-diff/pull/121
